/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 *
 * Generado con `npm run generate:types` (scripts/generate-types.mjs), que
 * añade UN transform al generador: `format: binary` sale como `Blob` y no
 * como `string`. El porqué, en ese fichero.
 */

export interface paths {
    "/billing/portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /api/billing/portal — Get Stripe Customer Portal URL
         * @description **Exige la habilidad `central`** en el token, y que la cuenta sea de desarrollador.
         *
         *     Allows users to manage payment methods, view invoices, cancel subscriptions.
         */
        post: operations["billing.portal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/sponsorship": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /api/billing/sponsorship — asumir la licencia de un cliente
         * @description **Exige la habilidad `central`** en el token, y que la cuenta sea de desarrollador.
         *
         *     Mismo mecanismo para las dos figuras intermediarias (gestoría y
         *     desarrollador): una suscripción de canal con `quantity` = asientos y una
         *     factura consolidada, en vez de N suscripciones sueltas.
         */
        post: operations["billing.sponsor"];
        /**
         * DELETE /api/billing/sponsorship — soltar un cliente patrocinado
         * @description **Exige la habilidad `central`** en el token, y que la cuenta sea de desarrollador.
         */
        delete: operations["billing.releaseSponsorship"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/desarrollador/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /api/desarrollador/overview — cartera y cuota
         * @description **Exige la habilidad `desarrollador`** en el token, y que la cuenta sea de desarrollador.
         *
         *     Cada fila de `cartera` lleva `origen`: el client OAuth que trajo al
         *     tenant (la atribución del alta, #726) o `null` si entró por otro
         *     camino. Es lo que el panel central enseña como «entró por tu app X».
         *
         *     El cuerpo se declara entero porque el generador no sigue el `map()`
         *     sobre la colección de tenants: en la 1.3.0 `cartera` salía como una
         *     lista de `string` y el panel no podía tipar ni una fila.
         */
        get: operations["desarrollador.overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/desarrollador/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /api/desarrollador/salud — estado técnico de sus integraciones
         * @description **Exige la habilidad `desarrollador`** en el token, y que la cuenta sea de desarrollador.
         *
         *     Lo que un desarrollador necesita y un asesor no: si sus clients siguen
         *     usándose, si sus webhooks llegan y si tiene propuestas esperando decisión
         *     del cliente. Todo son METADATOS de la integración — último uso, códigos
         *     de estado, contadores. Nunca el contenido de lo que viaja.
         */
        get: operations["desarrollador.salud"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/desarrollador/facturacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /api/desarrollador/facturacion — su suscripción de canal
         * @description **Exige la habilidad `desarrollador`** en el token, y que la cuenta sea de desarrollador.
         */
        get: operations["desarrollador.facturacion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/desarrollador/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description **Exige la habilidad `desarrollador`** en el token, y que la cuenta sea de desarrollador. */
        get: operations["desarrolladorLink.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/desarrollador/links/generate-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description **Exige la habilidad `desarrollador`** en el token, y que la cuenta sea de desarrollador. */
        post: operations["desarrolladorLink.generateCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/desarrollador/links/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aceptar la solicitud de una instancia
         * @description **Exige la habilidad `desarrollador`** en el token, y que la cuenta sea de desarrollador.
         *
         *     Aquí está LA diferencia con la gestoría: no se crea ningún usuario dentro
         *     del tenant ni se toca `tenant_users`. El vínculo solo pasa a `active`.
         */
        post: operations["desarrolladorLink.accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/desarrollador/links/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description **Exige la habilidad `desarrollador`** en el token, y que la cuenta sea de desarrollador. */
        post: operations["desarrolladorLink.reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/desarrollador/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET — los clients OAuth de este desarrollador
         * @description **Exige la habilidad `desarrollador`** en el token, y que la cuenta sea de desarrollador.
         */
        get: operations["desarrolladorLink.clients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/desarrollador/clients/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST — «este client es mío»
         * @description **Exige la habilidad `desarrollador`** en el token, y que la cuenta sea de desarrollador.
         *
         *     Requiere demostrar posesión del client, no solo conocer su id: el
         *     client_id viaja en cada pantalla de consentimiento y en la URL de
         *     autorización, así que es público de facto. Para un client confidencial se
         *     exige el secret; para uno público (PKCE, sin secret) solo puede
         *     reclamarlo quien lo registró desde un tenant vinculado a esta cuenta.
         */
        post: operations["desarrolladorLink.claimClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/desarrollador/tenants/{slug}/activaciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /api/desarrollador/tenants/{slug}/activaciones — lo activado a este cliente
         * @description **Exige la habilidad `desarrollador`** en el token, y que la cuenta sea de desarrollador.
         *
         *     `base` es su licencia (el asiento de canal); `items`, los módulos y apps
         *     activos con lo que cuestan al integrador al mes; `total` lo suma.
         */
        get: operations["integradorActivacion.index"];
        put?: never;
        /**
         * POST /api/desarrollador/tenants/{slug}/activaciones — activar algo al cliente
         * @description **Exige la habilidad `desarrollador`** en el token, y que la cuenta sea de desarrollador.
         *
         *     `kind` ∈ `base|module|app` y `slug` (`pimia` para la base). La base es el
         *     asiento: la primera vez devuelve `checkout_url` (el canal aún no tiene
         *     suscripción) y las siguientes es un asiento más. Un módulo o una app
         *     exigen la base viva (`409 base_required`) y se cobran al integrador
         *     como una partida más de su canal, sin prorrateo, en la factura del mes;
         *     el módulo se enciende en el acto y la app la instala el cliente por
         *     empresa sin pasar por caja. Idempotente: lo ya activo contesta
         *     `already_active: true` sin tocar Stripe (y remata lo que se quedó a
         *     medias); un módulo que el cliente ya tenía encendido por su cuenta
         *     contesta `already_active` con `inherited: true` y NO se cobra. Cortes, con su código en
         *     `error`: `not_the_integrator` (403), `not_sellable` (422),
         *     `base_required` y `channel_required` (409), `channel_subscription_ending`
         *     (402), `stripe_price_missing` (503), `stripe_addon_failed` (502),
         *     `addon_busy` (409), `module_not_enabled` (422).
         *
         *     Contesta **201** cuando activa algo nuevo y **200** cuando ya estaba
         *     activo o cuando lo que devuelve es el Checkout del canal; los dos
         *     `return` llevan el código escrito para que el generador publique los
         *     dos cuerpos (⛔ no con `@response 201`: esa etiqueta Scramble la lee
         *     como el TIPO `201` y el cuerpo desaparece del contrato — pasó en la
         *     1.3.0, lo midió el estudio del panel central). `return_url` (1.4.0):
         *     a dónde vuelve desde el Checkout; solo se acepta el origen del panel
         *     central o el del ápice.
         */
        post: operations["integradorActivacion.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/desarrollador/tenants/{slug}/activaciones/{kind}/{item}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * DELETE /api/desarrollador/tenants/{slug}/activaciones/{kind}/{item} — dar de baja
         * @description **Exige la habilidad `desarrollador`** en el token, y que la cuenta sea de desarrollador.
         *
         *     Un módulo se apaga en el acto y deja de cobrarse desde la próxima
         *     factura; una app se desinstala de todas las empresas del cliente. La
         *     base suelta el asiento (el cliente baja a Free y con él caen sus
         *     activaciones). Cortes: `not_active` (404), `has_dependents` (422),
         *     `not_the_integrator` (403).
         */
        delete: operations["integradorActivacion.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/desarrollador/catalogo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /api/desarrollador/catalogo — el catálogo propio y lo que se puede revender
         * @description **Exige la habilidad `desarrollador`** en el token, y que la cuenta sea de desarrollador.
         *
         *     `perfil` y `currency` van a `null` mientras el integrador no haya
         *     guardado nada; `disponibles` dice qué puede entrar en `items` (es la
         *     lista contra la que valida el `PUT`).
         */
        get: operations["integradorCatalogo.show"];
        /**
         * PUT /api/desarrollador/catalogo — reemplaza el catálogo entero
         * @description **Exige la habilidad `desarrollador`** en el token, y que la cuenta sea de desarrollador.
         *
         *     Cabecera (nombre comercial, soporte, moneda ISO 4217 y enlace de
         *     contratación por defecto) y filas (`kind` ∈ `base|module|app`, `slug`,
         *     `price_cents` en subunidades de esa moneda —siempre una cifra—,
         *     `contract_url` propio opcional, `enabled`). Una fila que no venga deja de
         *     existir. Un slug que no sea revendible responde 422.
         */
        put: operations["integradorCatalogo.update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/desarrollador/dominios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /api/desarrollador/dominios — los nombres de login del integrador
         * @description **Exige la habilidad `desarrollador`** en el token, y que la cuenta sea de desarrollador.
         */
        get: operations["integradorDominio.index"];
        put?: never;
        /**
         * POST /api/desarrollador/dominios — declarar un nombre de login
         * @description **Exige la habilidad `desarrollador`** en el token, y que la cuenta sea de desarrollador.
         *
         *     `slug` es la etiqueta interna (`login-<slug>.<dominio central>`, de 1 a
         *     32 caracteres `a-z0-9-`, única en Pimia) y `host` el nombre público que
         *     el integrador sirve. Un nombre bajo un dominio de Pimia responde 422
         *     (`host`), igual que uno que ya declaró otro integrador. La respuesta
         *     trae `proxy_secret`, que el proxy manda en `X-Pimia-Login-Secret`: se
         *     genera aquí y se rota retirando el nombre y declarándolo otra vez.
         *
         *     Sin `@response 201`: Scramble la lee como el tipo `201` y el cuerpo
         *     —con el `proxy_secret`— desaparecía del contrato (1.3.0). El cuerpo
         *     sale de `presentar()`, que el generador sí lee.
         */
        post: operations["integradorDominio.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/desarrollador/dominios/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * DELETE /api/desarrollador/dominios/{slug} — retirar un nombre de login
         * @description **Exige la habilidad `desarrollador`** en el token, y que la cuenta sea de desarrollador.
         *
         *     Desde ese momento el host interno contesta 404 y el proxy del
         *     integrador deja de tener a dónde reenviar. 404 si el nombre no es suyo.
         */
        delete: operations["integradorDominio.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/desarrollador/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /api/desarrollador/tokens — los tokens de máquina vivos
         * @description **Exige la habilidad `desarrollador`** en el token, y que la cuenta sea de desarrollador.
         */
        get: operations["integradorToken.index"];
        put?: never;
        /**
         * POST /api/desarrollador/tokens — acuñar un token de máquina
         * @description **Exige la habilidad `desarrollador`** en el token, y que la cuenta sea de desarrollador.
         *
         *     `name` es para reconocerlo en la lista («webhook de producción»). El
         *     token en claro (`token`) se devuelve UNA vez: Pimia solo guarda su hash.
         *     Pide la sesión del integrador (403 `session_required` con un token de
         *     máquina): uno filtrado no acuña hermanos.
         *
         *     El cuerpo del 201 se escribe LITERAL y sin `@response`: Scramble lee
         *     esa etiqueta como el tipo `201` y el token en claro desaparecía del
         *     contrato (1.3.0; medido por el estudio del panel central).
         */
        post: operations["integradorToken.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/desarrollador/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * DELETE /api/desarrollador/tokens/{id} — revocar un token de máquina
         * @description **Exige la habilidad `desarrollador`** en el token, y que la cuenta sea de desarrollador.
         *
         *     404 si no es suyo o no es de máquina (una sesión del panel se cierra
         *     desde el panel, no desde aquí).
         */
        delete: operations["integradorToken.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{slug}/transfer-ownership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /api/tenants/{slug}/transfer-ownership — traspaso de propiedad
         * @description **Exige la habilidad `central`** en el token, y que la cuenta sea de desarrollador.
         *
         *     Versión mínima y deliberada: el dueño actual (o el superadmin) pasa la
         *     propiedad a un usuario que YA pertenece a la instancia. No es un flujo
         *     self-service con aceptación por parte del destinatario; es la pieza que
         *     faltaba para que el desarrollador que dio de alta un tenant pueda
         *     devolvérselo a su cliente.
         *
         *     Por qué hace falta: la decisión nº 4 del fundador permite al
         *     desarrollador crear tenants, y entonces él queda de owner. El rescate por
         *     impago («tu proveedor dejó de pagar; asume tú la licencia») exige que el
         *     cliente pueda ser dueño de lo suyo — si no, la instancia queda de rehén.
         */
        post: operations["tenant.transferOwnership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{slug}/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /api/tenants/{slug}/users — List users with access to this tenant
         * @description **Exige la habilidad `central`** en el token, y que la cuenta sea de desarrollador.
         */
        get: operations["tenant.users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant-invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /api/tenant-invitations — Invitaciones de la gestoría autenticada
         * @description **Exige la habilidad `central`** en el token, y que la cuenta sea de desarrollador.
         */
        get: operations["tenantInvitation.index"];
        put?: never;
        /**
         * POST /api/tenant-invitations — Crear y enviar una invitación (gestoría)
         * @description **Exige la habilidad `central`** en el token, y que la cuenta sea de desarrollador.
         */
        post: operations["tenantInvitation.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant-invitations/{invitation}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * DELETE /api/tenant-invitations/{invitation} — Revocar una invitación
         * @description **Exige la habilidad `central`** en el token, y que la cuenta sea de desarrollador.
         */
        delete: operations["tenantInvitation.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * IntegradorCatalogoRequest
         * @description Cuerpo de `PUT /api/desarrollador/catalogo`: el catálogo del integrador
         *     ENTERO —cabecera y filas—, que sustituye al que hubiera.
         *
         *     Lo que se defiende: que cada fila revenda algo que existe (un módulo
         *     opcional ofrecido, una app activa del catálogo de Pimia, o `base`/`pimia`),
         *     que no haya dos filas para lo mismo, que el precio sea SIEMPRE una cifra en
         *     subunidades (👤, 2026-09-06: sin filas «incluido»; 0 vale) y que la moneda
         *     sea un código ISO 4217. El precio minorista no se valida contra ningún
         *     precio de Pimia: es del integrador (regla 4 del punto 12).
         */
        IntegradorCatalogoRequest: {
            nombre_comercial: string;
            /** Format: uri */
            soporte_url?: string | null;
            /** Format: email */
            soporte_email?: string | null;
            currency: string;
            /** Format: uri */
            contract_url?: string | null;
            items: {
                /** @enum {string} */
                kind: "base" | "module" | "app";
                slug: string;
                price_cents: number;
                /** Format: uri */
                contract_url?: string | null;
                enabled?: boolean;
            }[];
        };
    };
    responses: {
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Unauthenticated */
        AuthenticationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Not found */
        ModelNotFoundException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "billing.portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    return_url?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            portal_url: string;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "No billing account found. Subscribe to a plan first.";
                    };
                };
            };
        };
    };
    "billing.sponsor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    tenant_slug: string;
                    plan_id: number;
                    /**
                     * @description A dónde vuelve desde el Checkout del canal: el panel central en
                     *     React (1.4.0). Solo se acepta su origen; si no, el panel Vue.
                     */
                    return_url?: string | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        message: "Completa el alta de tu suscripción de canal para activar el patrocinio." | "Asumida la licencia de la instancia.";
                        data: {
                            checkout_url: string | null;
                        };
                    } | string;
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "billing.releaseSponsorship": {
        parameters: {
            query: {
                tenant_slug: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Has dejado de pagar la licencia de esta instancia.";
                    } | string;
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "desarrollador.overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            cartera: {
                                id: string;
                                name: string;
                                status: string;
                                plan: string | null;
                                created_at: string | null;
                                trial_ends_at: string | null;
                                relacion: string;
                                billing_mode: string | null;
                                la_pago_yo: boolean;
                                marca_blanca: boolean;
                                origen: {
                                    client_id: string;
                                    name: string;
                                } | null;
                            }[];
                            resumen: {
                                total: number;
                                activos: number;
                                suspendidos: number;
                            };
                            cuota: {
                                usada: number;
                                limite: number;
                                ilimitada: boolean;
                            };
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "desarrollador.salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            clients: {
                                client_id: string;
                                name: string;
                                revoked_at: string;
                                tokens_vivos: number;
                                ultimo_uso: string | null;
                            }[];
                            webhooks: {
                                id: number;
                                tenant_id: string | null;
                                /** @description La URL es del desarrollador, no del cliente: puede verla. */
                                url: string;
                                events: unknown[];
                                /** Format: date-time */
                                disabled_at: string | null;
                                consecutive_failures: number;
                                entregas_7d: {
                                    delivered: number;
                                    pending: number;
                                    dead: number;
                                };
                            }[];
                            approvals: {
                                abiertas: number;
                                por_tenant: {
                                    tenant_id: string;
                                    abiertas: number;
                                }[];
                            } | {
                                abiertas: number;
                                por_tenant: string[];
                            };
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "desarrollador.facturacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            canal: {
                                estado: string;
                                asientos: number;
                                /**
                                 * @description Por la partida del PLAN: con un añadido mayorista el
                                 *     canal es multiprecio y `$canal->quantity` es NULL.
                                 */
                                quantity: number;
                                /** @description Si divergen, manda el número de asientos: es lo servido. */
                                descuadre: boolean;
                                termina_en: string;
                            } | null;
                            asientos: {
                                tenant_id: string;
                                rol: string;
                                en_mora: boolean;
                                /** Format: date-time */
                                gracia_hasta: string | null;
                                /** Format: date-time */
                                suspendido_desde: string | null;
                            }[];
                            en_mora: number;
                            /**
                             * @description Lo que paga en añadidos mayoristas de toda su cartera
                             *     (módulos y apps activados a sus clientes). Por el servicio
                             *     inyectado y no por `app()`: el generador del contrato solo
                             *     ve la forma del retorno si sabe qué clase lo devuelve
                             *     (en la 1.3.0 salía como `string`).
                             */
                            anadidos: {
                                activaciones: number;
                                total_cents: number;
                                total: string;
                                por_tenant: unknown[];
                            };
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "desarrolladorLink.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: number;
                            link_code: string;
                            status: string;
                            tenant: {
                                id: string;
                                name: string;
                                status: string;
                            } | null;
                            requester: {
                                id: number;
                                name: string;
                                email: string;
                            } | null;
                            /** Format: date-time */
                            requested_at: string | null;
                            /** Format: date-time */
                            accepted_at: string | null;
                            /** Format: date-time */
                            revoked_at: string | null;
                            /** Format: date-time */
                            created_at: string | null;
                        }[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "desarrolladorLink.generateCode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Código de vinculación generado.";
                        data: {
                            id: number;
                            link_code: string;
                            status: string;
                            tenant: {
                                id: string;
                                name: string;
                                status: string;
                            } | null;
                            requester: {
                                id: number;
                                name: string;
                                email: string;
                            } | null;
                            /** Format: date-time */
                            requested_at: string | null;
                            /** Format: date-time */
                            accepted_at: string | null;
                            /** Format: date-time */
                            revoked_at: string | null;
                            /** Format: date-time */
                            created_at: string | null;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "desarrolladorLink.accept": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Vinculación aceptada.";
                        data: {
                            id: number;
                            link_code: string;
                            status: string;
                            tenant: {
                                id: string;
                                name: string;
                                status: string;
                            } | null;
                            requester: {
                                id: number;
                                name: string;
                                email: string;
                            } | null;
                            /** Format: date-time */
                            requested_at: string | null;
                            /** Format: date-time */
                            accepted_at: string | null;
                            /** Format: date-time */
                            revoked_at: string | null;
                            /** Format: date-time */
                            created_at: string | null;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            /**
             * @description An error
             *
             *     An error
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error overview.
                         * @example La solicitud no está pendiente.
                         */
                        message: string;
                    } | {
                        /**
                         * @description Error overview.
                         * @example La solicitud no tiene instancia asociada.
                         */
                        message: string;
                    };
                };
            };
        };
    };
    "desarrolladorLink.reject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Solicitud rechazada.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            /** @description An error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error overview.
                         * @example La solicitud no está pendiente.
                         */
                        message: string;
                    };
                };
            };
        };
    };
    "desarrolladorLink.clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            client_id: string;
                            name: string;
                            confidential: boolean;
                            scope: string;
                            registration_tenant_id: string;
                            revoked_at: string;
                            created_at: string;
                        }[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "desarrolladorLink.claimClient": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    client_id: string;
                    client_secret?: string | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        error: "ownership_not_provable";
                        /** @constant */
                        message: "Este client es público (sin secret). Solo puedes reclamarlo si se registró desde una instancia vinculada a tu cuenta.";
                    } | {
                        /** @constant */
                        error: "invalid_client_secret";
                        /** @constant */
                        message: "El client_secret no coincide. Solo quien lo tiene puede reclamar el client.";
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        error: "already_owned";
                        /** @constant */
                        message: "Ese client ya pertenece a otra cuenta.";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "integradorActivacion.index": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            base: {
                                active: boolean;
                                price_cents: number | null;
                                price: string | null;
                                plan: string | null;
                            };
                            items: {
                                kind: string;
                                slug: string;
                                name: string;
                                active_since: string;
                                price_cents: number | null;
                                price: string | null;
                            }[];
                            total_cents: number;
                            total: string;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "integradorActivacion.store": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    kind: "base" | "module" | "app";
                    slug: string;
                    plan_id?: number | null;
                    return_url?: string | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        message: "Completa el alta de tu suscripción de canal para activar la licencia de este cliente." | "El cliente ya lo tenía encendido por su cuenta: no se te cobra ni se le toca." | "Ya estaba activo." | "Activado: se cobra en tu canal desde la próxima factura.";
                        data: {
                            already_active: boolean;
                            inherited: boolean;
                            checkout_url: string | null;
                            quantity: number | null;
                            activation: {
                                [key: string]: unknown;
                            } | null;
                        };
                    } | string;
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        message: "Completa el alta de tu suscripción de canal para activar la licencia de este cliente." | "El cliente ya lo tenía encendido por su cuenta: no se te cobra ni se le toca." | "Ya estaba activo." | "Activado: se cobra en tu canal desde la próxima factura.";
                        data: {
                            already_active: boolean;
                            inherited: boolean;
                            checkout_url: string | null;
                            quantity: number | null;
                            activation: {
                                [key: string]: unknown;
                            } | null;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "integradorActivacion.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                kind: string;
                item: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                        data: {
                            quantity: number | null;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "integradorCatalogo.show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            perfil: {
                                nombre_comercial: string;
                                soporte_url: string | null;
                                soporte_email: string | null;
                            } | null;
                            currency: string | null;
                            contract_url: string | null;
                            items: {
                                kind: string;
                                slug: string;
                                name: string;
                                description: string | null;
                                price_cents: number;
                                price: string | null;
                                contract_url: string | null;
                                enabled: boolean;
                            }[];
                            disponibles: {
                                base: {
                                    slug: string;
                                    name: string;
                                    description: string | null;
                                    wholesale_price_cents: number | null;
                                    wholesale_price: string | null;
                                }[];
                                modules: {
                                    slug: string;
                                    name: string;
                                    description: string | null;
                                    wholesale_price_cents: number | null;
                                    wholesale_price: string | null;
                                }[];
                                apps: {
                                    slug: string;
                                    name: string;
                                    description: string | null;
                                    wholesale_price_cents: number | null;
                                    wholesale_price: string | null;
                                }[];
                            };
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "integradorCatalogo.update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntegradorCatalogoRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            perfil: {
                                nombre_comercial: string;
                                soporte_url: string | null;
                                soporte_email: string | null;
                            } | null;
                            currency: string | null;
                            contract_url: string | null;
                            items: {
                                kind: string;
                                slug: string;
                                name: string;
                                description: string | null;
                                price_cents: number;
                                price: string | null;
                                contract_url: string | null;
                                enabled: boolean;
                            }[];
                            disponibles: {
                                base: {
                                    slug: string;
                                    name: string;
                                    description: string | null;
                                    wholesale_price_cents: number | null;
                                    wholesale_price: string | null;
                                }[];
                                modules: {
                                    slug: string;
                                    name: string;
                                    description: string | null;
                                    wholesale_price_cents: number | null;
                                    wholesale_price: string | null;
                                }[];
                                apps: {
                                    slug: string;
                                    name: string;
                                    description: string | null;
                                    wholesale_price_cents: number | null;
                                    wholesale_price: string | null;
                                }[];
                            };
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "integradorDominio.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            slug: string;
                            host: string;
                            enabled: boolean;
                            login_url: string;
                            upstream: string;
                            proxy_secret: string;
                            proxy: string;
                            created_at: string | null;
                        }[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "integradorDominio.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    slug: string;
                    host: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Nombre declarado. Apunta tu proxy al upstream y reenvía el nombre público en X-Forwarded-Host.";
                        data: {
                            slug: string;
                            host: string;
                            enabled: boolean;
                            login_url: string;
                            upstream: string;
                            proxy_secret: string;
                            proxy: string;
                            created_at: string | null;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "integradorDominio.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "integradorToken.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: number;
                            name: string;
                            abilities: string[];
                            last_used_at: string | null;
                            expires_at: string | null;
                            created_at: string | null;
                        }[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "integradorToken.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Token creado. Guárdalo ahora: no se vuelve a enseñar.";
                        data: {
                            token: string;
                            id: number;
                            name: string;
                            abilities: unknown[];
                            last_used_at: string | null;
                            expires_at: string | null;
                            created_at: string | null;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        error: "session_required";
                        /** @constant */
                        message: "Un token de máquina no acuña otros: entra con tu cuenta (o usa el token de la sesión del panel) para crearlo.";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "integradorToken.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "tenant.transferOwnership": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    user_id: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                        data: {
                            tenant_id: string;
                            owner_id: number;
                            /** @enum {string} */
                            billing_mode: "sponsor" | "self";
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            /** @description An error */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error overview.
                         * @example Solo el propietario actual puede traspasar la instancia.
                         */
                        message: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "tenant.users": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "tenantInvitation.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            email: string;
                            company_name: string;
                            billing: string;
                            status: string;
                            expires_at: string;
                            accepted_tenant_id: string;
                            accepted_at: string;
                            created_at: string;
                        }[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "tenantInvitation.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    company_name?: string | null;
                    /**
                     * @description `despacho|cliente` es el vocabulario de la gestoría; `sponsor|self`
                     *     el general del modelo de facturación (Tenant::BILLING_*). Se
                     *     aceptan los dos y se guarda el de siempre, para no partir la
                     *     columna ni el asistente en dos.
                     * @enum {string}
                     */
                    billing?: "despacho" | "cliente" | "sponsor" | "self";
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                        data: {
                            id: string;
                            email: string;
                            company_name: string;
                            billing: string;
                            status: string;
                            expires_at: string;
                            accepted_tenant_id: string;
                            accepted_at: string;
                            created_at: string;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            /** @description An error */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        error: "invitation_quota_exceeded";
                        message: string;
                    } | {
                        /**
                         * @description Error overview.
                         * @example Solo las gestorías y los desarrolladores pueden enviar invitaciones a clientes.
                         */
                        message: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "No se pudo enviar el email de invitación. Revisa la configuración de correo e inténtalo de nuevo.";
                    };
                };
            };
        };
    };
    "tenantInvitation.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The invitation ID */
                invitation: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Invitación revocada.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Solo se pueden revocar invitaciones pendientes.";
                    };
                };
            };
        };
    };
}
