/**
 * Genera `src/api.ts` desde el OpenAPI, con UNA corrección al generador.
 *
 * Antes esto era una línea en `package.json`:
 *
 *     openapi-typescript ../spec/pimia-api-v1.json -o src/api.ts
 *
 * y sigue siendo eso mismo, salvo por el `transform` de abajo — que la CLI no
 * admite, porque es un hook de la API de Node. Ese es el único motivo de que
 * este fichero exista.
 *
 * ## Qué corrige, y por qué no es cosmético
 *
 * `openapi-typescript` traduce `{"type":"string","format":"binary"}` a **
 * `string`**. Es su comportamiento documentado y para un OpenAPI cualquiera es
 * defendible: JSON no tiene bytes. Pero en este contrato hay **nueve** sitios
 * con `format: binary`, y ninguno de los nueve es una cadena:
 *
 *   - siete son campos de un cuerpo `multipart/form-data` —el justificante de
 *     un gasto, el documento de una recibida, el fichero de un extracto
 *     bancario, el membrete, el certificado de firma, el avatar—, o sea lo que
 *     se **manda** como fichero;
 *   - dos son respuestas `application/octet-stream` —descargar el membrete,
 *     descargar el documento de una recibida—, o sea lo que se **recibe** como
 *     fichero.
 *
 * Con `string`, el tipo generado dice que se puede subir un fichero pasando
 * texto. No se puede: el servidor valida `file` y responde 422. Y al revés, un
 * integrante que sí tenga un `File` y quiera hacer lo correcto **no compila**.
 * O sea que el tipo no describía el contrato: describía una limitación del
 * generador, y encima empujaba hacia la llamada equivocada.
 *
 * `Blob` sirve para las dos direcciones y para los dos tiempos: `File` extiende
 * `Blob` en la librería del DOM y en Node ≥ 20, así que un `File` encaja donde
 * se pide un `Blob` sin ceremonia, y una descarga se lee con `.arrayBuffer()`
 * o `.text()`.
 *
 * ⚠️ Esto **cambia tipos publicados**, así que va en una versión menor con su
 * nota en el CHANGELOG. No rompe a nadie en la práctica: hasta esta versión el
 * cliente no sabía mandar multipart —serializaba todo cuerpo con
 * `JSON.stringify`—, así que ninguna llamada que hoy funcione depende de que
 * ese campo fuera `string`.
 */

import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'
import ts from 'typescript'

const SPEC = fileURLToPath(new URL('../../spec/pimia-api-v1.json', import.meta.url))
const SALIDA = fileURLToPath(new URL('../src/api.ts', import.meta.url))

/** `Blob`, como nodo del AST que el generador escribe tal cual. */
const BLOB = ts.factory.createTypeReferenceNode('Blob')

const documento = JSON.parse(await readFile(SPEC, 'utf8'))

let corregidos = 0

const ast = await openapiTS(documento, {
  transform(schemaObject) {
    if (schemaObject.type === 'string' && schemaObject.format === 'binary') {
      corregidos++

      /* `nullable` sale del propio esquema: hay campos binarios opcionales
         —`AvatarRequest.avatar`— que el contrato declara `["string","null"]`,
         y perder el `null` aquí sería cambiar el contrato en vez de traducirlo. */
      return schemaObject.nullable === true
        ? ts.factory.createUnionTypeNode([
            BLOB,
            ts.factory.createLiteralTypeNode(ts.factory.createNull()),
          ])
        : BLOB
    }

    return undefined
  },
})

if (corregidos === 0) {
  /* Falla en vez de generar en silencio: si el generador cambia de forma —o el
     spec deja de marcar los binarios— lo que sale es un `api.ts` con los nueve
     campos vueltos a `string`, y eso pasaría una revisión sin que nadie lo
     note. Que se caiga aquí es el aviso. */
  console.error(
    '\n✖ El transform de `format: binary` no ha tocado NADA.\n\n' +
      '  O el spec ha dejado de declarar binarios, o el hook del generador ha\n' +
      '  cambiado de forma. Sin él, los campos de fichero vuelven a salir como\n' +
      '  `string` y el tipo dice que se puede subir un fichero mandando texto.\n' +
      '  Mira `scripts/generate-types.mjs` antes de seguir.\n',
  )
  process.exit(1)
}

/* La cabecera la escribe la CLI y `astToString` no, así que se repone aquí:
   es lo único que le dice a quien abra `src/api.ts` —19 000 líneas— que no lo
   edite a mano. Se añade la línea del transform, porque un fichero que dice
   «generado por openapi-typescript» y contiene `Blob` donde el generador pone
   `string` mandaría a buscar el error en el sitio equivocado. */
const CABECERA = `/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 *
 * Generado con \`npm run generate:types\` (scripts/generate-types.mjs), que
 * añade UN transform al generador: \`format: binary\` sale como \`Blob\` y no
 * como \`string\`. El porqué, en ese fichero.
 */

`

await writeFile(SALIDA, CABECERA + astToString(ast), 'utf8')

console.log(`✓ tipos regenerados; ${corregidos} campos binarios escritos como Blob`)
